version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    executor: aws-cli/default
    steps:
      - checkout
      - run:
          command: echo $(AWS_Access_Key_ID)
      - run:
          command: echo $(AWS_Secret_Access_Key)
      - run:
          command: echo $(Default_region_name).  
      - run:
          name: Ensure backend infrastructure exist
          command: |
            pwd
            ls -la
            aws cloudformation deploy \
            aws --region us-east-1 cloudformation deploy \
              --template-file template.yml \
              --stack-name my-stack
workflows:
  my_workflow:
    jobs:
      - create_infrastructure